### PR TITLE
Add react-refresh to overrides.

### LINKED ISSUE #38: [cli] Hot reloading doesn't work for web with expo-router
An update is needed to the overrides section fo package json to add the react-refresh package version as noted here:
image

Source: https://docs.expo.dev/router/reference/static-rendering/

I will make a PR for this.

### PR DESCRIPTION
**Pull request by mwarger**
Fixes #38

Tested locally - hot reloading works correctly on web after this update.

### CODE REVIEW

**Comment by frankcalise** [comment]
This will only work for `npm` package manager correct?

**Comment by mwarger** [comment]
> This will only work for `npm` package manager correct?

Correct.  That seems to be the default baked-in.  If there's a way to switch that then we can add a condition for yarn.

**Comment by frankcalise** [comment]
@mwarger cool - and `bun` uses those two as well so that's covered. idk about `pnpm`?

**Comment by mwarger** [comment]
Pnpm uses overrides, so it's covered.

**Review by danstepanov — APPROVED** [review]
LGTM

**Pull request merged**
