### PR TITLE
chore(cli): fix bun:test ts error

### PR DESCRIPTION
**Pull request by frankcalise**
## Describe your PR

- Fixes the ts error under importing from "bun:test"

image

### CODE REVIEW

**Review by sammoore — COMMENTED** [review]
The new tsconfig seems to break `bun run build` for me and in CI, due to conflicting types from `bun-types` and `@types/node`, the latter of which are getting imported because they are a dependency of some other packages...

...but `@types/node` is actually what we want in `cli/tsconfig.json`, since the TypeScript output of the `cli/` could be run on anyone's machine with or without using bun, so `@types/node` are what we want available, not `bun-types`. We can't run `bun` libraries from within the CLI code.

So, rather than adding `__tests__/` to the `cli/tsconfig.json` and `bun-types` to that config, I suggest just adding an inline TypeScript reference at the top of `__tests__/cli-integration.test.ts` for them, like so:

```typescript
/// <reference types="bun-types" />
```

**Comment by sammoore** [comment]
So it appears since I cloned this branch, that my local **_repo_** just can't `bun run build` anymore, due to the same `bun-types`/`@types/node` conflicting types error, no matter the HEAD I checkout. The solution I posted in the comment directly above does work in a fresh clone. I'm not sure if typescript is caching something regarding input files...

**Comment by frankcalise** [comment]
@sammoore There's some config details wrt bun here: https://bun.sh/docs/typescript#suggested-compileroptions

Should we try those?

**Comment by sammoore** [comment]
> @sammoore There's some config details wrt bun here: https://bun.sh/docs/typescript#suggested-compileroptions
> 
> Should we try those?

@frankcalise maybe if it's used in a separate `tsconfig.json` specifically targeting the `__tests__/`. But the rest of `cli/` should not because the `tsc` build output for the actual CLI's source may or may not run in bun (e.g. it can run on the user's machine via `npx` / etc).

The original issue was due to IntelliSense, but by adding `__tests__/` to the same `cli/tsconfig.json`, it's now trying to build the tests as part of the rest of the CLI. We are running the tests with bun, so we don't need them compiled by TypeScript. We also don't want `bun-types` available within plain `cli/` code (the other change made to the `tsconfig`).

IntelliSense does make use of `tsconfig` to do it's thing, but I'm not sure if we could configure different build targets or use a separate `tsconfig.json` that editors will automatically pick up. 

I think I fixed my machine with whatever weird build cache issue was happening and the solution [I posted above](https://github.com/danstepanov/create-expo-stack/pull/118#pullrequestreview-1789832045) should work. This would work assuming we revert any changes to the `tsconfig.json`, that way it doesn't "`include:`" the tests folder, so that IntelliSense uses a default configuration for those files. It's not as good as having a separate `tsconfig.json` for the `__tests__` though, limiting the number of settings/overrides possible with inline references.

**Comment by frankcalise** [comment]
Sure I'll set up the test specific tsconfig and see how it operates

**Review by sammoore — APPROVED** [review]
LGTM!

**Review by danstepanov — APPROVED** [review]
Tests need their own tsconfig, LGTM

**Pull request merged**
