### PR TITLE
fix(cli): expo-router dupe stack import

### LINKED ISSUE #68: [cli] Stack imported from expo-router twice
## Description
- When the the project is done generating, you'll notice two lines with `import { Stack } from "expo-router";`
- To reproduce: `npx create-expo-stack@latest my-expo-app --expo-router --tabs --stylesheet --npm`

## How
- Fix the `_layout.tsx.ejs` under `cli\src\templates\packages\expo-router\tabs\app` to not contain this duplicate line

### PR DESCRIPTION
**Pull request by frankcalise**
- Closes #68

### CODE REVIEW

**Comment by danstepanov** [comment]
Thanks Frank! Can you run `bunx changeset` and include that in your commit here? We will try to automate this step in the future.

**Comment by frankcalise** [comment]
Any way we don't run doc and web CI if unchanged? Or is it generating pages based on CLI contents?

**Comment by danstepanov** [comment]
@frankcalise can you rebase this with `beta`?

**Comment by danstepanov** [comment]
> Any way we don't run doc and web CI if unchanged? Or is it generating pages based on CLI contents?

we don't auto generate pages

**Pull request closed without merging**
