### PR TITLE
Fix/expo import alias

### PR DESCRIPTION
**Pull request by gabimoncha**
## Description

Running cli with `--expo-router` will create project without `src` folder.
But `--import-alias` option still uses `src/*` in tsconfig.

## Motivation and Context

This PR fixes this conflict reduce dev effort

## How Has This Been Tested?

With `--react-navigation`

folder structure             |  tsconfig.json
:-------------------------:|:-------------------------:
  |  

With `--expo-router`

folder structure             |  tsconfig.json
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by danstepanov** [comment]
@frankcalise can you review this as you implemented this functionality originally?

**Comment by frankcalise** [comment]
@danstepanov yeah this looks ok to me. it certainly works

the other way of doing it would be if you wanted to have an `src` directory in an expo-router project (and `app` would contain the routes) then it would be more about fixing the expo router template rather than this change.

but we can revisit that if that becomes the plan later

**Comment by frankcalise** [comment]
@gabimoncha nice work, thank you for the screenshots!

**Comment by danstepanov** [comment]
@gabimoncha can you rebase your branch with the latest changes from my `main` branch?

**Comment by gabimoncha** [comment]
Done!

**Pull request merged**
