### PR TITLE
feat: eas flag for dev client setup

### PR DESCRIPTION
**Pull request by dannyhw**
## Description

Aims to add an option for initialising a project with eas 

## Motivation and Context

Simpler eas setup

## Screenshots (if appropriate):

https://github.com/danstepanov/create-expo-stack/assets/3481514/fc722af9-b888-4679-ae0a-a2202d28fc38

adjusted output

image

### CODE REVIEW

**Comment by dannyhw** [comment]
I think potentially we could run prebuild for the user which would also get them to configure the bundle identifiers and generate the ios/android folders. The only reason I didn't add it is because you could probably get by with just letting eas generate those on the cloud

**Comment by danstepanov** [comment]
@dannyhw is this ready for review based on our last discussion?

**Comment by dannyhw** [comment]
@danstepanov hey, had a really busy week so haven't had a chance to iterate on it since then. There's a few changes I'd like to make still.

**Comment by dannyhw** [comment]
@danstepanov Hey sorry for the delay I had a lot going on. Made some updates based on what we spoke about.

**Comment by danstepanov** [comment]
@dannyhw Can you make this part of the core CLI questions? Not just a flag.

**Comment by dannyhw** [comment]
Hey @danstepanov, it should come up as a question already. I made it a flag more because I wasn't sure if it fit as a "package".

**Comment by danstepanov** [comment]
@dannyhw mind rebasing with `main`? I'll merge and take it from there :)

**Comment by dannyhw** [comment]
@danstepanov merged in changes and conflicts resolved 👍

**Review by danstepanov — APPROVED** [review]
LGTM

**Pull request merged**
