### PR TITLE
Added vercel analytics to docs

### LINKED ISSUE #82: [docs] add vercel analytics
Screenshot 2023-11-27 at 10 26 40 PM

https://vercel.com/docs/analytics/quickstart

### PR DESCRIPTION
**Pull request by kratos-respawned**
Incorporated Vercel analytics into the docs. This is my initial experience with Changesets, and I’m not entirely sure how to utilize it. Since I don’t have the Bun runtime installed, I manually added the changes.
Fixes #82

### CODE REVIEW

**Comment by danstepanov** [comment]
@kratos-respawned you can remove the changeset stuff as that only applies to changes made to the `cli` folder

**Comment by kratos-respawned** [comment]
> @kratos-respawned you can remove the changeset stuff as that only applies to changes made to the `cli` folder

done

**Review by danstepanov — APPROVED** [review]
LGTM

**Comment by danstepanov** [comment]
@kratos-respawned please rebase with `beta`

**Review by danstepanov — CHANGES_REQUESTED** [review]
please rebase <3

**Review by danstepanov — APPROVED** [review]
LGTM

**Review by danstepanov — APPROVED** [review]
LGTM

**Pull request merged**
