### PR TITLE
Real time Github Star Counts

### PR DESCRIPTION
**Pull request by Sahad-09**
Lmk if anything additional needed or with any changes

### CODE REVIEW

**Comment by danstepanov** [comment]
Thanks for this! Can you remove the unused code and console logs as well as provide screenshots of the functionality? Also let's use our own orange/yellow instead of the t3 colors.

**Comment by danstepanov** [comment]
Please also ensure that the vercel build step passes

**Comment by Sahad-09** [comment]
image
is this okay ? And how do I check vercel's build steps ? Is there anyway to do it manually through my system or will I come to know only after I send PR

**Comment by Sahad-09** [comment]
image

**Comment by Sahad-09** [comment]
Looks like it got passed

**Comment by danstepanov** [comment]
@Sahad-09 this is a good first pass.

To clarify, similar to the T3 version, this github star count component needs to:

- [ ] be clickable (click should navigate user to github repo)
- [ ] base border color and star color should be same as the "Star us on github" button in the center top
- [ ] have a hover style that changes the border color and star color the same way as the "Star us on github" button
- [ ] hide itself when viewed on mobile

**Comment by Sahad-09** [comment]
I'm trying to get that arrow thingy. Gimme some time

**Comment by Sahad-09** [comment]
> * [x ]  be clickable (click should navigate user to github repo)
> * [ x]  base border color and star color should be same as the "Star us on github" button in the center top
> * [ x]  have a hover style that changes the border color and star color the same way as the "Star us on github" button
> * [ x]  hide itself when viewed on mobile
> * [ x]  have this little arrow on the side

**Comment by danstepanov** [comment]
@Sahad-09 build is failing, can you please get the build to pass?
```
[02:06:39.654] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[02:06:39.769] Cloning github.com/danstepanov/create-expo-stack (Branch: main, Commit: 96d8933)
[02:06:40.196] Cloning completed: 426.524ms
[02:06:47.369] Restored build cache
[02:06:47.450] Running "vercel build"
[02:06:47.946] Vercel CLI 32.5.5
[02:06:48.105] > Detected Turbo. Adjusting default settings...
[02:06:50.229] Running "install" command: `bun install`...
[02:06:50.271] bun install v1.0.11 (f7f6233e)
[02:06:50.437]  + create-expo-stack@workspace:cli
[02:06:50.437]  + create-expo-stack-web@workspace:www
[02:06:50.437]  + eslint@8.53.0
[02:06:50.437] 
[02:06:50.437]  21 packages installed [183.00ms]
[02:06:50.443] Detected Next.js version: 13.4.6
[02:06:50.444] Running "turbo run build"
[02:06:50.564] • Packages in scope: create-expo-stack-web
[02:06:50.565] • Running build in 1 packages
[02:06:50.566] • Remote caching enabled
[02:06:50.700] create-expo-stack-web:build: cache miss, executing 04366eb4379dab59
[02:06:50.704] create-expo-stack-web:build: $ next build
[02:06:51.270] create-expo-stack-web:build: - info Creating an optimized production build...
[02:06:52.912] create-expo-stack-web:build: - error Failed to find font override values for font `Geologica`
[02:06:59.376] create-expo-stack-web:build: - error Failed to find font override values for font `Geologica`
[02:07:00.429] create-expo-stack-web:build: - info Compiled successfully
[02:07:00.431] create-expo-stack-web:build: - info Linting and checking validity of types...
[02:07:02.654] create-expo-stack-web:build: - warn The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
[02:07:04.062] create-expo-stack-web:build: 
[02:07:04.062] create-expo-stack-web:build: Failed to compile.
[02:07:04.063] create-expo-stack-web:build: 
[02:07:04.063] create-expo-stack-web:build: ./src/app/utilities/FetchGithubStar.ts
[02:07:04.063] create-expo-stack-web:build: 2:37  Error: Replace `"react"` with `'react'`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 5:1  Error: Replace `··` with `↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 7:1  Error: Replace `··` with `↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 8:1  Error: Replace `····` with `↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 9:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 10:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 11:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 12:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 13:1  Error: Replace `··············` with `↹↹↹↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 14:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 15:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
[02:07:04.063] create-expo-stack-web:build: 16:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 17:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 18:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 19:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 21:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 22:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 23:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 24:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 25:1  Error: Replace `····` with `↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 27:1  Error: Replace `····` with `↹↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 28:1  Error: Replace `··` with `↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 30:1  Error: Replace `··` with `↹`  prettier/prettier
[02:07:04.064] create-expo-stack-web:build: 
[02:07:04.064] create-expo-stack-web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
[02:07:07.580] create-expo-stack-web:build: error: script "build" exited with code 1 (SIGHUP)
[02:07:07.581] create-expo-stack-web:build: ERROR: command finished with error: command (/vercel/path0/www) bun run build exited (1)
[02:07:07.581] create-expo-stack-web#build: command (/vercel/path0/www) bun run build exited (1)
[02:07:07.582] 
[02:07:07.582]   Tasks:    0 successful, 1 total
[02:07:07.582]  Cached:    0 cached, 1 total
[02:07:07.582]    Time:    17.075s 
[02:07:07.582] Summary:    /vercel/path0/.turbo/runs/2YQi4FlUwnsoqam6AcC8ZdYnB2E.json
[02:07:07.582]  Failed:    create-expo-stack-web#build
[02:07:07.582] 
[02:07:07.583]  ERROR  run failed: command  exited (1)
[02:07:07.590] Error: Command "turbo run build" exited with 1
[02:07:07.905] ```

**Comment by Sahad-09** [comment]
> @Sahad-09 build is failing, can you please get the build to pass?
> 
> ```
> [02:06:39.654] Running build in Washington, D.C., USA (East) – iad1 (Hive)
> [02:06:39.769] Cloning github.com/danstepanov/create-expo-stack (Branch: main, Commit: 96d8933)
> [02:06:40.196] Cloning completed: 426.524ms
> [02:06:47.369] Restored build cache
> [02:06:47.450] Running "vercel build"
> [02:06:47.946] Vercel CLI 32.5.5
> [02:06:48.105] > Detected Turbo. Adjusting default settings...
> [02:06:50.229] Running "install" command: `bun install`...
> [02:06:50.271] bun install v1.0.11 (f7f6233e)
> [02:06:50.437]  + create-expo-stack@workspace:cli
> [02:06:50.437]  + create-expo-stack-web@workspace:www
> [02:06:50.437]  + eslint@8.53.0
> [02:06:50.437] 
> [02:06:50.437]  21 packages installed [183.00ms]
> [02:06:50.443] Detected Next.js version: 13.4.6
> [02:06:50.444] Running "turbo run build"
> [02:06:50.564] • Packages in scope: create-expo-stack-web
> [02:06:50.565] • Running build in 1 packages
> [02:06:50.566] • Remote caching enabled
> [02:06:50.700] create-expo-stack-web:build: cache miss, executing 04366eb4379dab59
> [02:06:50.704] create-expo-stack-web:build: $ next build
> [02:06:51.270] create-expo-stack-web:build: - info Creating an optimized production build...
> [02:06:52.912] create-expo-stack-web:build: - error Failed to find font override values for font `Geologica`
> [02:06:59.376] create-expo-stack-web:build: - error Failed to find font override values for font `Geologica`
> [02:07:00.429] create-expo-stack-web:build: - info Compiled successfully
> [02:07:00.431] create-expo-stack-web:build: - info Linting and checking validity of types...
> [02:07:02.654] create-expo-stack-web:build: - warn The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
> [02:07:04.062] create-expo-stack-web:build: 
> [02:07:04.062] create-expo-stack-web:build: Failed to compile.
> [02:07:04.063] create-expo-stack-web:build: 
> [02:07:04.063] create-expo-stack-web:build: ./src/app/utilities/FetchGithubStar.ts
> [02:07:04.063] create-expo-stack-web:build: 2:37  Error: Replace `"react"` with `'react'`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 5:1  Error: Replace `··` with `↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 7:1  Error: Replace `··` with `↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 8:1  Error: Replace `····` with `↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 9:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 10:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 11:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 12:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 13:1  Error: Replace `··············` with `↹↹↹↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 14:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 15:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
> [02:07:04.063] create-expo-stack-web:build: 16:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 17:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 18:1  Error: Replace `············` with `↹↹↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 19:1  Error: Replace `··········` with `↹↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 21:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 22:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 23:1  Error: Replace `········` with `↹↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 24:1  Error: Replace `······` with `↹↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 25:1  Error: Replace `····` with `↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 27:1  Error: Replace `····` with `↹↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 28:1  Error: Replace `··` with `↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 30:1  Error: Replace `··` with `↹`  prettier/prettier
> [02:07:04.064] create-expo-stack-web:build: 
> [02:07:04.064] create-expo-stack-web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
> [02:07:07.580] create-expo-stack-web:build: error: script "build" exited with code 1 (SIGHUP)
> [02:07:07.581] create-expo-stack-web:build: ERROR: command finished with error: command (/vercel/path0/www) bun run build exited (1)
> [02:07:07.581] create-expo-stack-web#build: command (/vercel/path0/www) bun run build exited (1)
> [02:07:07.582] 
> [02:07:07.582]   Tasks:    0 successful, 1 total
> [02:07:07.582]  Cached:    0 cached, 1 total
> [02:07:07.582]    Time:    17.075s 
> [02:07:07.582] Summary:    /vercel/path0/.turbo/runs/2YQi4FlUwnsoqam6AcC8ZdYnB2E.json
> [02:07:07.582]  Failed:    create-expo-stack-web#build
> [02:07:07.582] 
> [02:07:07.583]  ERROR  run failed: command  exited (1)
> [02:07:07.590] Error: Command "turbo run build" exited with 1
> [02:07:07.905] ```
> ```

Done

**Comment by danstepanov** [comment]
Cool, will wait for @PickleNik to sign off/finalize here

**Comment by danstepanov** [comment]
@Sahad-09 thanks for the contribution, we ended up going with this approach #93

**Pull request closed without merging**
