### PR TITLE
Add `@changesets/cli` and base GitHub Actions for auto-publishing

### PR DESCRIPTION
**Pull request by ernestoresende**
This PR implements the base for auto-publishing trough GitHub Actions using `@changesets/cli` and some custom scripts to manage `canary` releases.

See the quickstart guide for changesets for reference on how they work: https://github.com/changesets/changesets/blob/main/docs/intro-to-using-changesets.md

### Recommended workflow:

The way in which canary releases are handled with the additions in this PR assumes that `canary` is your main branch, and `main` is a locked branch reserved only for regular releases, meaning that the only commits reaching `main` should come from a pull request to merge `canary` into `main`.

- Releases from commits to `main` branch will only be triggered when changeset entries are present in `.changesets/*`. When present, changesets will be "consumed" in order to update the release notes and `CHANGELOG.md`, and publish the package to the NPM registry. The package will be published with the `latest` tag, and the version of the `package.json` will be bumped following semver (`{major}.{minor}.{patch}`), based on the changes specified by changesets.

- Releases from commits to `canary` branch will be published on each new commit with the `canary` tag, and the version of the `package.json` will be `{major}.{minor}.{patch}-canary-{commitHash}`.

Outside of the `main` branch, contributors can create a new changeset entry on any other branches, and they will only be "consumed" once those changes hits `main`. Version bumps caused by new version releases in `main` should always be merged back to `canary`.

Remember that changesets are not tied to commits, so you don't need to create a new changeset on each commit. They will, however, take the hash of the commit where they were commited in order to build an entry on the release notes:

Changeset entry in the release notes

### Requirements:

@danstepanov, for this to work in the current implementation, we need:
- A `canary` branch;
- Valid `GITHUB_TOKEN` and `NPM_TOKEN` secret keys available to GitHub Actions in the repository scope.

### Observations:

- Keep in mind that the use of `canary` is merely a suggestion, we can tag name to whatever makes sense here (eg.: `prerelease`, `beta`, `alpha`);
- As of now, these changes only includes CI tasks related to publishing, but you can integrate testing, linting and formatting as part of the CI pipeline for both kinds of releases.
- If you want to follow a approach that more closely resembles what Next.js does with their publishing pipeline (canary releases are also controlled by changesets, not by new commits), that would require a new approach for the canary part of the publishing, but the contribution workflow would largely remain the same.

### CODE REVIEW

**Comment by danstepanov** [comment]
Reviewing today

**Comment by danstepanov** [comment]
@ernestoresende just waiting on that excalidraw diagram from you

**Comment by ernestoresende** [comment]
Will be working on it sometime this week and imbue into this PR with additions to `CONTRIBUTING.md` as soon as I'm done.

**Comment by ernestoresende** [comment]
@danstepanov Managed to get a minimal workflow illustration going.

Publishing workflow

 but I now realize that we have a problem regarding how the current `canary` publishing is coded: it's hardcoded to make a patch bump, regardless if previous changesets are making an actual patch bump, or a minor/major instead.

Still trying to figure out how I'll tackle this. In the meanwhile, I need a confirmation if we're going to move in the monorepo space, as I would like to tackle that problem first, given that it affects how the tooling for publishing will be handled.

**Comment by ernestoresende** [comment]
- Waiting for #32 before getting back to this

**Comment by danstepanov** [comment]
@ernestoresende can you update this PR based on the new monorepo structure?

**Comment by ernestoresende** [comment]
Sure thing, I'll do some work on getting `canary` releases to work correctly as illustrated in the graphic, and we should be good to go with this.

**Comment by ernestoresende** [comment]
Woopsie caused by trying to rebase current `main` with my outdated fork branch from the web interface. Reopening for further work

**Comment by danstepanov** [comment]
@ernestoresende let's go through this on vc, flying today but should be online

**Comment by ernestoresende** [comment]
@danstepanov Updated to achieve the following:

- Use Bun for dependency installs and build tasks on CI;
- Update the publishing pipeline to correctly bump the versions based on existing changesets;

This should accurately reflect the workflow described by the graphic. Also updated the graphic to represent our shift from using `canary` to `beta` as the tag for the "push and release channel":

**Review by danstepanov — APPROVED** [review]
LGTM

**Pull request merged**
