### PR TITLE
Added Docs to the landing

### PR DESCRIPTION
**Pull request by hqasmei**

### CODE REVIEW

**Comment by danstepanov** [comment]
@hqasmei can you provide screenshots of what this looks like on web and mobile?

### Expectation on mobile

Hamburger menu on right replaces Github icon in nav bar. Clicking on it slides out a drawer with options that parallel the navigation in the docs, similar to T3.

https://github.com/danstepanov/create-expo-stack/assets/5482800/c75aa37b-8b15-4a43-8b1f-1909cf317922

### Expectation on web

"Docs" next to the right of the Github logo. Clicking on it navigates to https://docs.createexpostack.com.

**Comment by danstepanov** [comment]
Mobile looks off but web looks good

Screenshot 2023-12-17 at 9 16 33 PM

**Review by danstepanov — CHANGES_REQUESTED** [review]
just needs work on mobile

**Comment by hqasmei** [comment]
Screenshot 2023-12-17 at 9 51 51 PM
Screenshot 2023-12-17 at 9 51 57 PM

**Comment by hqasmei** [comment]
Here are screen shots for mobile docs, let me know if this is good.

Screenshot 2023-12-17 at 9 51 51 PM


Screenshot 2023-12-17 at 9 51 57 PM

**Comment by hqasmei** [comment]
Like this? Or hide the "Docs"?
Screenshot 2023-12-17 at 10 03 33 PM

**Comment by danstepanov** [comment]
More like this

test

**Comment by hqasmei** [comment]
Ah okay gotcha, I see what you mean. Will work on that

**Comment by danstepanov** [comment]
Screenshot 2023-12-18 at 9 46 41 PM
@hqasmei can you remove the create expo stack logo in the drawer on mobile?

**Comment by hqasmei** [comment]
Just made the change

**Review by danstepanov — APPROVED** [review]
LGTM

**Pull request merged**
