### PR TITLE
Update contributors in readme

### PR DESCRIPTION
**Pull request by Hacksore**
attempt to update contributors in readme automatically.

### CODE REVIEW

**Comment by danstepanov** [comment]
@Hacksore I tried to do this via https://github.com/danstepanov/create-expo-stack/commit/cfc261a737f0545cc40caf03bfa5a1466be013ab but it doesn't seem to work 🤔

**Comment by Hacksore** [comment]
> @Hacksore I tried to do this via [cfc261a](https://github.com/danstepanov/create-expo-stack/commit/cfc261a737f0545cc40caf03bfa5a1466be013ab) but it doesn't seem to work 🤔

try invoking a contributor job manually and see what happens. But one thing to keep in mind i your `README.md` is not in the root so you might need to configure that.

https://github.com/danstepanov/create-expo-stack/actions/workflows/contributors.yaml

**Comment by Hacksore** [comment]
[docs](https://github.com/marketplace/actions/contribute-list) say you can use `readme_path`.

**Comment by danstepanov** [comment]
@Hacksore ¯\_(ツ)_/¯  https://github.com/danstepanov/create-expo-stack/blob/a6e5da5075e62652c8897bd381cd465137c70fe6/.github/workflows/contributors.yaml#L54

**Comment by Hacksore** [comment]
@danstepanov it's probably needing to be `readme_path: cli/README.md` as it's going to be relative to where the `actions/checkout` pulls down the code.

Then once you update that, kick off another workflow dispatch 🤞.

Once we get that working I can close this PR.

**Comment by danstepanov** [comment]
@Hacksore I got it working, you were using `master` instead of `main`. Very progressive of you.

**Pull request closed without merging**
