### PR TITLE
refactor: rename drawer to tabs + drawer

### LINKED ISSUE #144: Rename "drawer" to "tabs + drawer"
When choosing a navigation type in the cli, you currently select between "stack", "tabs", or "drawer". This is misleading as "drawer" actually includes a tab controller as well.

### PR DESCRIPTION
**Pull request by neerajkumarc**
closes #144

### CODE REVIEW

**Comment by danstepanov** [comment]
You'll need to also update the rest of the app to use "Drawer + Tabs". See `selectNavigationType.toLowercase()` or otherwise change the NavigationType to be "drawer + tabs". Please be sure to test that the flow still works by running the client prompt and selecting drawer + tabs.

**Comment by neerajkumarc** [comment]
Thanks for the heads up! I've updated all instances of "drawer" to "tabs + drawer". Let me know if there's anything else you'd like me to check.

**Comment by danstepanov** [comment]
```
test create-expo-stack
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

✔ What do you want to name your project? (my-expo-app) ·
✔ Would you like to use TypeScript with this project? (Y/n) · true
Good call, now using TypeScript! 🚀
✔ What would you like to use for Navigation? · React Navigation
✔ What type of navigation would you like to use? · Tabs + Drawer
Great, we'll use React Navigation!
✔ What would you like to use for styling? · Nativewind
You'll be styling with ease using Tailwind.
✔ What would you like to use for authentication? · None
No problem, skipping authentication for now.
✔ Which package manager would you like to use? · yarn

Your project configuration:
{
  projectName: 'my-expo-app',
  packages: [
    {
      name: 'react-navigation',
      type: 'navigation',
      options: { type: 'tabs + drawer' }
    },
    { name: 'nativewind', type: 'styling' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'yarn'
  }
}

To recreate this project, run:
  npx create-expo-stack my-expo-app --react-navigation --drawer --nativewind --importAlias --yarn

Initializing your project...

Copying base assets...

Installing dependencies using yarn...```

<img width="561" alt="Screenshot 2023-12-25 at 2 27 34 AM" src="https://github.com/danstepanov/create-expo-stack/assets/5482800/8d02b1a0-588c-4389-9bde-c6e9f59e141d">

```
iOS Bundling complete 4296ms
iOS Bundling complete 4249ms
 ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 ERROR  Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes
 ERROR  Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes```

**Comment by danstepanov** [comment]
Does running this work for you?

**Comment by neerajkumarc** [comment]
Whoops! Missed a few spots in my last update. 🙈 Fixed up those references to "drawer" in the other files. Should be good to go now. Let me know if there's anything else I can do.


This is what it now looks at my end:

wsltom@LAPTOP-D8K6RQOU:~$ create-expo-stack
                          _
   ___  _ __  ___   __ _ | |_  ___
  / __|| '__|/ _ \ / _` || __|/ _ \
 | (__ | |  |  __/| (_| || |_|  __/
  \___||_|   \___| \__,_| \__|\___|
   ___ __  __ _ __    ___
  / _ \\ \/ /| '_ \  / _ \
 |  __/ >  < | |_) || (_) |
  \___|/_/\_\| .__/  \___/
       _     |_|        _
  ___ | |_  __ _   ___ | | __
 / __|| __|/ _` | / __|| |/ /
 \__ \| |_| (_| || (__ |   <
 |___/ \__|\__,_| \___||_|\_\

✔ What do you want to name your project? (my-expo-app) ·
✔ Would you like to use TypeScript with this project? (Y/n) · true
Good call, now using TypeScript! 🚀
✔ What would you like to use for Navigation? · React Navigation
✔ What type of navigation would you like to use? · Tabs + Drawer
Great, we'll use React Navigation!
✔ What would you like to use for styling? · Nativewind
You'll be styling with ease using Tailwind.
✔ What would you like to use for authentication? · None
No problem, skipping authentication for now.
✔ Which package manager would you like to use? · bun

Your project configuration:
{
  projectName: 'my-expo-app',
  packages: [
    {
      name: 'react-navigation',
      type: 'navigation',
      options: { type: 'tabs + drawer' }
    },
    { name: 'nativewind', type: 'styling' }
  ],
  flags: {
    noGit: false,
    noInstall: false,
    overwrite: false,
    importAlias: true,
    packageManager: 'bun'
  }
}

To recreate this project, run:
  npx create-expo-stack my-expo-app --react-navigation --drawer --nativewind --importAlias --bun

Initializing your project...

Copying base assets...

Installing dependencies using bun...

WhatsApp Image 2023-12-25 at 5 38 39 PM

**Comment by danstepanov** [comment]
@neerajkumarc Apologies for the delayed response. I just realized that the way the drawer is implemented, it actually is just a drawer. We should implement a "Drawer + Tab" template for navigation, if you are interested in giving that a shot. It would be a mirror of the existing "tabs" option but with an added drawer that allows you to pull up a page that is not part of either tab. Here is a video of the current drawer implementation to show that it does not use tabs atm. 

Separately, we should change the name of the screens from "Tab One" and "Tab Two" to "Screen 1" and "Screen 2" if it is using the "drawer" option.

https://github.com/danstepanov/create-expo-stack/assets/5482800/6291d177-b3f0-4a30-96c0-fe8cba106d6f

**Comment by asapMaki** [comment]
Can I jump in on this one, I have template that I have started on personally that has drawer and tabs amongst many other things which we can add to this project too.

https://github.com/danstepanov/create-expo-stack/assets/30200380/6ad4db22-dcf6-4729-a73e-8ee8dccac887

**Comment by danstepanov** [comment]
closing in favor of https://github.com/danstepanov/create-expo-stack/pull/159

**Pull request closed without merging**
